export const HERO_DIORAMAS_BRITISH = {
  conwy_castle: {
    style: 'crusader',
    fidelityLabel: 'hero-burg',
    historicalMode: 'surveyed',
    sourceConfidence: 'hoch',
    focus: { x: -2, y: 9, z: 2 },
    cameraRadius: 40,
    terrainModel: 'custom',
    notes: 'Conwy lebt von seiner langen Felskante, dem Wasserkontakt zur Muendung und der klaren Zweiteilung von aeusserem und innerem Ward. Das Diorama liest die Burg daher als gestreckte Kette von Tuermern auf einem felsigen Kamm statt als zentrischen Ring.',
    sources: ['CADW surveys of Conwy Castle', 'Master James of St George studies'],
    components: [
      {
        type: 'WATER_PLANE',
        x: -20, z: 6, y: 0.08, w: 34, d: 42,
        label: 'Conwy-Muendung',
        info: 'Die Muendung sicherte Conwy strategisch doppelt: Schutz auf der Westseite und Versorgung ueber das Wassertor. Solange Schiffe anlegen konnten, blieb die Burg lebensfaehig.',
      },
      {
        type: 'TERRAIN_STACK',
        x: 2, z: 0, y: 0,
        footprint: [
          { x: -17, z: -13 }, { x: -12, z: -16 }, { x: 15, z: -15 }, { x: 19, z: -8 }, { x: 20, z: 10 }, { x: 14, z: 16 }, { x: -6, z: 16 }, { x: -13, z: 12 }, { x: -15, z: 0 },
        ],
        layers: [{ scale: 1.12, h: 1.3 }, { scale: 1.03, h: 1.15 }, { scale: 0.96, h: 0.95 }],
        label: 'Felsruecken von Conwy',
        info: 'Conwy sitzt auf einem langgestreckten Felsruecken direkt ueber der Muendung. Der Burgkoerper folgt deshalb dem Ruecken und weitet sich nicht kreisfoermig aus.',
      },
      {
        type: 'PLATEAU',
        x: 2.5, z: 0.8, y: 3.42, w: 31, d: 14, h: 0.6,
        label: 'Burgplateau von Conwy',
        info: 'Auf dem langgezogenen Plateau staffeln sich aeusserer Ward, innerer Ward und die Wohnbauten des Koenigs entlang der Felskante.',
      },
      {
        type: 'SLOPE_PATH',
        x1: 19.5, z1: 11.5, x2: 12.8, z2: 7.8, y1: 0.35, y2: 3.5, w: 3.2, thick: 0.2,
        label: 'Landseitiger Zugang',
        info: 'Der Zugang von Osten fuehrte ueber einen kontrollierten Anstieg in Richtung Vorburg. Auch in Conwy war der Weg zur Hauptpforte selbst schon Teil der Verteidigung.',
      },
      {
        type: 'SLOPE_PATH',
        x1: -9.8, z1: 7.5, x2: -18.8, z2: 12.5, y1: 3.45, y2: 0.3, w: 1.8, thick: 0.18,
        label: 'Wassertor-Abgang',
        info: 'Das Wassertor verband die Burg direkt mit der Muendung. Gerade diese Verbindung machte Conwy auch in Einschliessungssituationen widerstandsfaehig.',
      },
      {
        type: 'RING',
        y: 3.48,
        gate: {
          atIndex: 2, w: 3.5, d: 2.8, h: 7.5,
          label: 'Aeusseres Tor von Conwy',
          info: 'Der oestliche Hauptzugang in den aeusseren Ward war die zuerst sichtbare Verdichtung der Burg. Von hier musste jeder Angreifer unter Turm- und Mauerfeuer weiter in die Anlage hinein.',
        },
        points: [
          { x: -10.5, z: -5.8, r: 1.55, h: 8.5, label: 'Westturm NW', info: 'Nordwestlicher Turm ueber der Wasserseite.' },
          { x: -2.5, z: -6.3, r: 1.45, h: 8.0, label: 'Westturm NO', info: 'Nordseite des westlichen Burgabschnitts.' },
          { x: 7.0, z: -6.2, r: 1.55, h: 8.4, label: 'Osttor-Nordturm', info: 'Nordturm der landseitigen Torfront.' },
          { x: 13.8, z: -2.2, r: 1.55, h: 8.4, label: 'Aeusserer Ostturm', info: 'Oestlicher Flankierungsturm des aeusseren Wards.' },
          { x: 13.4, z: 4.8, r: 1.55, h: 8.4, label: 'Aeusserer SO-Turm', info: 'Suedoestliche Ecke des aeusseren Burgteils.' },
          { x: 6.8, z: 7.2, r: 1.55, h: 8.3, label: 'Osttor-Suedturm', info: 'Suedturm der Torfront mit Blick auf den Anmarsch.' },
          { x: -1.6, z: 7.6, r: 1.45, h: 8.0, label: 'Westturm SO', info: 'Suedseite des westlichen Abschnitts.' },
          { x: -10.0, z: 6.8, r: 1.55, h: 8.5, label: 'Westturm SW', info: 'Suedwestlicher Turm nahe Wassertor und Felskante.' },
        ],
        wall: { h: 6.1, thick: 0.95 },
      },
      {
        type: 'RING',
        y: 3.62,
        gate: {
          atIndex: 6, w: 3.0, d: 2.4, h: 7.2,
          label: 'Innerer Ward',
          info: 'Conwys innerer Ward ist keine vollstaendig getrennte Festung, aber doch klar als zweiter konzentrierter Verteidigungsraum lesbar. Hier lagen auch die koeniglichen Wohnraeume.',
        },
        points: [
          { x: -8.0, z: -4.6, r: 1.45, h: 8.2, label: 'Innerer NW-Turm', info: 'Nordwestturm des inneren Wards.' },
          { x: -1.2, z: -4.8, r: 1.35, h: 7.8, label: 'Innerer N-Mitte', info: 'Noerdlicher Zwischenpunkt des inneren Abschnitts.' },
          { x: 4.8, z: -4.7, r: 1.45, h: 8.0, label: 'Innerer NO-Turm', info: 'Nordostturm des inneren Wards.' },
          { x: 8.0, z: -0.4, r: 1.35, h: 7.6, label: 'Innerer O', info: 'Oestliche Verbindungszone zwischen den Wards.' },
          { x: 7.1, z: 5.0, r: 1.45, h: 8.0, label: 'Innerer SO-Turm', info: 'Suedoestlicher Turm des inneren Wards.' },
          { x: 1.2, z: 5.5, r: 1.35, h: 7.8, label: 'Innerer S-Mitte', info: 'Suedlicher Zwischenpunkt des inneren Bereichs.' },
          { x: -6.8, z: 5.2, r: 1.45, h: 8.2, label: 'Innerer SW-Turm', info: 'Suedwestturm des inneren Wards.' },
        ],
        wall: { h: 6.0, thick: 0.9 },
      },
      {
        type: 'SQUARE_TOWER',
        x: -2.8, z: 0.8, w: 6.5, d: 2.8, h: 4.8, y: 3.58,
        noRoof: true,
        label: 'Koenigsappartements',
        info: 'Die Wohnbauten Eduards I. machen Conwy zur Mischung aus Feldfestung und koeniglicher Residenz. Sie liegen im Diorama bewusst als langgezogener Baukoerper entlang des inneren Wards.',
      },
      {
        type: 'SQUARE_TOWER',
        x: -9.2, z: 4.8, w: 2.2, d: 1.7, h: 3.6, y: 3.5,
        label: 'Wassertor',
        info: 'Das Wassertor ist klein, aber strategisch ueberproportional wichtig. Ohne diese Oeffnung waere Conwy nur eine weitere steinerne Ringburg statt einer widerstandsfaehigen Seefestung.',
      },
    ],
  },
  harlech: {
    style: 'crusader',
    fidelityLabel: 'hero-burg',
    historicalMode: 'surveyed',
    sourceConfidence: 'hoch',
    focus: { x: -4, y: 10, z: 1 },
    cameraRadius: 42,
    terrainModel: 'custom',
    notes: 'Harlech wird als Felskante mit fast abgeschnittener West- und Nordseite inszeniert. Der Fokus liegt auf dem Gegensatz zwischen unnahbarem Seefelsen und der einen verwundbaren Ostflanke.',
    sources: ['CADW surveys of Harlech Castle', 'Edwardian castles in Wales studies'],
    components: [
      { type: 'WATER_PLANE', x: -22, z: 5, y: 0.06, w: 28, d: 40, label: 'Irische See / Kuestenzugang', info: 'Harlechs eigentliche Superkraft war lange Zeit die Verbindung zur See. Solange der Kuestenzugang offen blieb, konnte die kleine Garnison durchhalten.' },
      { type: 'TERRAIN_STACK', x: -2, z: 0, y: 0,
        footprint: [{ x: -18, z: -16 }, { x: -13, z: -19 }, { x: 6, z: -18 }, { x: 13, z: -14 }, { x: 16, z: -4 }, { x: 16, z: 11 }, { x: 7, z: 17 }, { x: -10, z: 17 }, { x: -17, z: 9 }],
        layers: [{ scale: 1.14, h: 1.5 }, { scale: 1.05, h: 1.3 }, { scale: 0.98, h: 1.1 }],
        label: 'Felsklippe von Harlech',
        info: 'Harlech steht auf einem steilen Kuestenfelsen. Das Diorama staffelt die Felsmasse bewusst nach Westen und Norden steiler ab als nach Osten, weil dort der einzige ernsthafte Zugang lag.',
      },
      { type: 'PLATEAU', x: -1.2, z: 0.5, y: 3.9, w: 18, d: 12, h: 0.65, label: 'Burgplateau von Harlech', info: 'Auf dem oberen Felskopf sitzt der kompakte, fast rechteckige Burgkoerper. Anders als bei Conwy ist Harlech noch staerker als kompakter Block lesbar.' },
      { type: 'SLOPE_PATH', x1: 14, z1: 1, x2: 8.2, z2: 1.2, y1: 0.3, y2: 4.0, w: 3.8, thick: 0.2, label: 'Ostzugang', info: 'Die Ostseite war Harlechs einzige realistische Angriffsrichtung. Jeder Belagerer musste genau hier seine Maschinen und Sturmkolonnen ansetzen.' },
      { type: 'SLOPE_PATH', x1: -8.8, z1: 5.8, x2: -18.5, z2: 14, y1: 4.0, y2: 0.3, w: 1.8, thick: 0.18, label: 'Seegang / Versorgungspfad', info: 'Der legendaere Weg zur See machte Harlech zu einer Ausnahmeerscheinung. Selbst mit minimaler Garnison blieb die Burg dadurch jahrelang versorgbar.' },
      { type: 'RING', y: 3.95,
        points: [
          { x: -8, z: -5.6, r: 1.85, h: 9.2, label: 'Nordwestturm', info: 'Eckturm ueber dem Felsabfall. Die Westseite war so schwer angreifbar, dass dieser Turm vor allem Beobachtung und Seezugang deckte.' },
          { x: 0.2, z: -5.8, r: 1.7, h: 8.6, label: 'Nordostturm', info: 'Noerdlicher Ostturm flankierte die verwundbarere Landseite.' },
          { x: 6.8, z: -1.2, r: 2.0, h: 9.8, label: 'Torhausturm Nord', info: 'Teil des maechtigen Osttorhauses. Hier verdichtete Harlech seine ganze landseitige Abwehr.' },
          { x: 6.8, z: 4.6, r: 2.0, h: 9.8, label: 'Torhausturm Sued', info: 'Zweiter Torturm der Ostfront. Zusammen mit dem noerdlichen Turm bildete er die staerkste kuenstliche Verteidigung der Anlage.' },
          { x: 0.6, z: 7.2, r: 1.7, h: 8.6, label: 'Suedostturm', info: 'Suedlicher Ostturm der Hauptkurtine.' },
          { x: -7.8, z: 7.4, r: 1.9, h: 9.3, label: 'Suedwestturm', info: 'Suedwestlicher Eckturm ueber der steilsten Felskante und dem Seegang.' },
        ],
        gate: { atIndex: 2, w: 3.8, d: 3.0, h: 8.3, label: 'Harlechs Osttorhaus', info: 'Das Osttorhaus ist die eigentliche Nahkampfmaschine der Burg. Jeder Angriff auf Harlech musste durch diesen Flaschenhals.' },
        wall: { h: 6.7, thick: 1.0 },
      },
      { type: 'SQUARE_TOWER', x: -1.8, z: 0.8, w: 5.8, d: 2.6, h: 4.4, y: 3.98, noRoof: true, label: 'Innerer Hof / Hallenbau', info: 'Der innere Burgraum blieb bewusst kompakt. Harlech war keine ausufernde Palastburg, sondern eine hoch effiziente Festung mit konzentrierten Abwehr- und Wohnzonen.' },
      { type: 'SQUARE_TOWER', x: -7.7, z: 4.8, w: 2.1, d: 1.7, h: 3.4, y: 3.95, label: 'Seetor', info: 'Das Seetor war unscheinbar, aber strategisch entscheidend. Ohne diesen Zugang waere die legendaere Langzeitverteidigung Harlechs nicht moeglich gewesen.' },
    ],
  },
};
