export const HERO_DIORAMAS_CITY = {
  constantinople: {
    style: 'crusader',
    fidelityLabel: 'mega-anlage',
    historicalMode: 'surveyed',
    sourceConfidence: 'hoch',
    focus: { x: 0, y: 7, z: 0 },
    cameraRadius: 46,
    terrainModel: 'custom',
    notes: 'Konstantinopel wird im Diorama bewusst als Landmauer-Ausschnitt mit Tiefe statt als komplette Stadt modelliert. Entscheidend sind Graben, Vormauer, Hauptmauer und der beruechtigte Kerkaporta-Bereich.',
    sources: ['Theodosian Walls studies', '1453 siege reconstructions'],
    components: [
      {
        type: 'WATER_PLANE',
        x: 0, z: 26, y: 0.05, w: 54, d: 10,
        label: 'Marmara / Stadtseite',
        info: 'Die Suedseite des Dioramas oeffnet sich zur Stadt- und Wasserwelt Konstantinopels. Die eigentliche Dramatik spielt sich aber entlang der Landmauer ab.',
      },
      {
        type: 'DITCH',
        x: 0, z: 0, y: 0.9, rTop: 24, rBot: 21.5, h: 1.1,
        label: 'Vorgraben',
        info: 'Vor den Theodosianischen Mauern lag ein breiter Graben. Schon bevor ein Angreifer die erste Mauer beruehrte, musste er also einen offenen Todeskorridor ueberwinden.',
      },
      {
        type: 'RING',
        y: 1.2,
        squareTowers: true,
        gate: {
          atIndex: 1, w: 2.0, d: 1.5, h: 3.5,
          label: 'Kerkaporta',
          info: 'Das kleine Tor, das 1453 offen geblieben sein soll, steht hier absichtlich nicht monumentaler als die Umgebung. Gerade seine Banalitaet macht die historische Pointe aus.',
        },
        points: [
          { x: 0, z: -22, r: 0.8, h: 3.2, label: 'Proteichisma N', info: 'Niedrige Vormauer als erste Abwehrlinie.' },
          { x: 2.6, z: -16, r: 0.8, h: 3.2, label: 'Proteichisma NNO', info: 'Noerdlicher Abschnitt der Vormauer.' },
          { x: 3, z: -8, r: 0.8, h: 3.2, label: 'Proteichisma Mitte-N', info: 'Mittlerer noerdlicher Abschnitt.' },
          { x: 3, z: 0, r: 0.8, h: 3.2, label: 'Proteichisma Mitte', info: 'Hier konzentrierten sich osmanische Angriffe.' },
          { x: 3, z: 8, r: 0.8, h: 3.2, label: 'Proteichisma Mitte-S', info: 'Suedlicher Mittelteil.' },
          { x: 2.6, z: 16, r: 0.8, h: 3.2, label: 'Proteichisma SSO', info: 'Suedlicher Abschnitt der Vormauer.' },
          { x: 0, z: 22, r: 0.8, h: 3.2, label: 'Proteichisma S', info: 'Suedende der Vormauer.' },
          { x: -2.6, z: 16, r: 0.8, h: 3.2, label: 'Proteichisma SSW', info: 'Suedwestabschnitt.' },
          { x: -3, z: 8, r: 0.8, h: 3.2, label: 'Proteichisma W-S', info: 'Westlicher Suedteil.' },
          { x: -3, z: 0, r: 0.8, h: 3.2, label: 'Proteichisma W-Mitte', info: 'Westliche Mitte.' },
          { x: -3, z: -8, r: 0.8, h: 3.2, label: 'Proteichisma W-N', info: 'Westlicher Nordteil.' },
          { x: -2.6, z: -16, r: 0.8, h: 3.2, label: 'Proteichisma NNW', info: 'Nahe der Kerkaporta.' },
        ],
        wall: { h: 2.5, thick: 0.6 },
      },
      {
        type: 'RING',
        y: 1.35,
        squareTowers: true,
        gate: {
          atIndex: 3, w: 3.0, d: 2.2, h: 6.0,
          label: 'Mittlere Mauer',
          info: 'Zwischen Vormauer und Hauptmauer lag der Peribolos, ein toedlicher Zwingerraum. Diese mittlere Linie machte Durchbrueche extrem schwer ausnutzbar.',
        },
        points: [
          { x: 0, z: -20, r: 1.0, h: 5.5, label: 'Mittelmauer N', info: 'Noerdlicher Turm der mittleren Mauer.' },
          { x: 4, z: -14, r: 1.0, h: 5.5, label: 'Mittelmauer NNO', info: 'Noerdlicher Zwischenabschnitt.' },
          { x: 5, z: -6, r: 1.0, h: 5.5, label: 'Mittelmauer NO', info: 'Noerdlicher Ostabschnitt.' },
          { x: 5, z: 0, r: 1.0, h: 5.5, label: 'Mittelmauer O-Mitte', info: 'Zentrales Segment der mittleren Mauer.' },
          { x: 5, z: 6, r: 1.0, h: 5.5, label: 'Mittelmauer SO', info: 'Suedoestlicher Abschnitt.' },
          { x: 4, z: 14, r: 1.0, h: 5.5, label: 'Mittelmauer SSO', info: 'Suedlicher Zwischenabschnitt.' },
          { x: 0, z: 20, r: 1.0, h: 5.5, label: 'Mittelmauer S', info: 'Suedende der mittleren Linie.' },
          { x: -4, z: 14, r: 1.0, h: 5.5, label: 'Mittelmauer SSW', info: 'Suedwestabschnitt.' },
          { x: -5, z: 6, r: 1.0, h: 5.5, label: 'Mittelmauer SW', info: 'Westlicher Suedteil.' },
          { x: -5, z: 0, r: 1.0, h: 5.5, label: 'Mittelmauer W-Mitte', info: 'Westliche Mitte.' },
          { x: -5, z: -6, r: 1.0, h: 5.5, label: 'Mittelmauer NW', info: 'Westlicher Nordteil.' },
          { x: -4, z: -14, r: 1.0, h: 5.5, label: 'Mittelmauer NNW', info: 'Nahe dem Kerkaporta-Bereich.' },
        ],
        wall: { h: 5.0, thick: 0.8 },
      },
      {
        type: 'RING',
        y: 1.6,
        squareTowers: true,
        gate: {
          atIndex: 4, w: 4.0, d: 3.0, h: 10.0,
          label: 'Innere Hauptmauer',
          info: 'Die eigentliche Theodosianische Hauptmauer war fast uneinnehmbar. Das Diorama zeigt sie als dominanteste Linie mit massivem Mesoteichion-Mittelteil.',
        },
        points: [
          { x: 0, z: -18, r: 1.4, h: 9.0, label: 'Hauptmauer N', info: 'Noerdlichster Turm der Hauptmauer.' },
          { x: 5.5, z: -12, r: 1.4, h: 9.5, label: 'Hauptmauer NNO', info: 'Noerdlicher Turm der Hauptmauer.' },
          { x: 7, z: -4, r: 1.4, h: 10, label: 'Hauptmauer NO', info: 'Abschnitt nahe der grossen osmanischen Beschusszone.' },
          { x: 7, z: 0, r: 1.4, h: 10, label: 'Mesoteichion', info: 'Das kritische Mittelstueck der Hauptmauer. Hier konzentrierten sich Kanonen und Sturmangriffe.' },
          { x: 7, z: 4, r: 1.4, h: 10, label: 'Hauptmauer SO', info: 'Suedoestlicher Mesoteichion-Abschnitt.' },
          { x: 5.5, z: 12, r: 1.4, h: 9.5, label: 'Hauptmauer SSO', info: 'Suedlicher Turm der Hauptmauer.' },
          { x: 0, z: 18, r: 1.4, h: 9.0, label: 'Hauptmauer S', info: 'Suedende der Landmauer.' },
          { x: -5.5, z: 12, r: 1.4, h: 9.5, label: 'Hauptmauer SSW', info: 'Suedwestlicher Abschnitt.' },
          { x: -7, z: 4, r: 1.4, h: 10, label: 'Hauptmauer SW', info: 'Westlicher Suedteil der Hauptmauer.' },
          { x: -7, z: 0, r: 1.4, h: 10, label: 'Hauptmauer W-Mitte', info: 'Westliche Mitte der Hauptmauer.' },
          { x: -7, z: -4, r: 1.4, h: 10, label: 'Hauptmauer NW', info: 'Westlicher Nordteil.' },
          { x: -5.5, z: -12, r: 1.4, h: 9.5, label: 'Hauptmauer NNW', info: 'Nahe dem Blachernae-Abschnitt.' },
          { x: -2, z: -16, r: 1.6, h: 11, label: 'Blachernae-Palastturm', info: 'Sonderturm des Blachernae-Bereichs, nahe dem beruechtigten Nebentor.' },
          { x: 2, z: -16, r: 1.4, h: 9.5, label: 'Hauptmauer NNO 2', info: 'Zweiter noerdlicher Grossabschnitt.' },
        ],
        wall: { h: 8.5, thick: 1.5 },
      },
    ],
  },
};
